#!/bin/bash
#PBS -q gpu
#PBS -l ngpus=2
#PBS -l ncpus=6
#PBS -l walltime=12:00:00
#PBS -l mem=15GB
#PBS -l jobfs=250Mb
#PBS -l software=vasp
#PBS -j oe
#PBS -N NiAl

module load vasp/5.4.4

hostname

export CUDA_VISIBLE_DEVICES=0,1
mkdir $PBS_JOBFS/nvidia-mps
export CUDA_MPS_PIPE_DIRECTORY=$PBS_JOBFS/nvidia-mps 
mkdir $PBS_JOBFS/nvidia-log
export CUDA_MPS_LOG_DIRECTORY=$PBS_JOBFS/nvidia-log 
nvidia-cuda-mps-control -d

cd $PBS_O_WORKDIR

mpirun vasp_std-gpu > vasp.out

